name = "testing_project"
location = 'C:\Users\carst\Projects\iron-coder\iron-coder-projects\testing_project'
current_view = "BoardsView"

[system.main_board]
name = "Feather RP2040"
manufacturer = "Adafruit"
is_main_board = true
standard = "Feather"
cpu = "Cortex-M0"
ram = 264
flash = 8000
bsp = "iron-coder-feather-rp2040-bsp"
required_crates = ["adafruit-feather-rp2040", "embedded-hal", "embedded-time", "cortex-m-rt", "cortex-m", "panic-halt"]
related_crates = ["smart-leds", "ws2812-pio"]

[[system.main_board.pinout]]
pins = [0, 1]

[system.main_board.pinout.interface]
iface_type = "UART"
direction = "Bidirectional"

[[system.main_board.pinout]]
pins = [8, 9]

[system.main_board.pinout.interface]
iface_type = "I2C"
direction = "Output"

[[system.peripheral_boards]]
name = "PropMaker Featherwing"
manufacturer = "Adafruit"
is_main_board = false
standard = "Feather"
bsp = "iron-coder-featherwing-propmaker-bsp"
related_crates = ["lis3dh"]

[[system.peripheral_boards.pinout]]
pins = [5, 9]
ident = "Accelerometer"

[system.peripheral_boards.pinout.interface]
iface_type = "I2C"
direction = "Input"

[[system.connections]]

[system.connections.start_board]
name = "Feather RP2040"
manufacturer = "Adafruit"
is_main_board = true
standard = "Feather"
cpu = "Cortex-M0"
ram = 264
flash = 8000
bsp = "iron-coder-feather-rp2040-bsp"
required_crates = ["adafruit-feather-rp2040", "embedded-hal", "embedded-time", "cortex-m-rt", "cortex-m", "panic-halt"]
related_crates = ["smart-leds", "ws2812-pio"]

[[system.connections.start_board.pinout]]
pins = [0, 1]

[system.connections.start_board.pinout.interface]
iface_type = "UART"
direction = "Bidirectional"

[[system.connections.start_board.pinout]]
pins = [8, 9]

[system.connections.start_board.pinout.interface]
iface_type = "I2C"
direction = "Output"

[system.connections.end_board]
name = "PropMaker Featherwing"
manufacturer = "Adafruit"
is_main_board = false
standard = "Feather"
bsp = "iron-coder-featherwing-propmaker-bsp"
related_crates = ["lis3dh"]

[[system.connections.end_board.pinout]]
pins = [5, 9]
ident = "Accelerometer"

[system.connections.end_board.pinout.interface]
iface_type = "I2C"
direction = "Input"

[system.connections.interface_mapping]
pins = [5, 9]
ident = "Accelerometer"

[system.connections.interface_mapping.interface]
iface_type = "I2C"
direction = "Input"

[graph_editor]
selected_nodes = []

[[graph_editor.graph.nodes]]
version = 0

[[graph_editor.graph.nodes]]
version = 13

[graph_editor.graph.nodes.value]
label = "PropMaker Featherwing"
inputs = [["I2C : Input", { idx = 1, version = 13 }]]
outputs = []

[graph_editor.graph.nodes.value.id]
idx = 1
version = 13

[graph_editor.graph.nodes.value.user_data]
name = "PropMaker Featherwing"
manufacturer = "Adafruit"
is_main_board = false
standard = "Feather"
bsp = "iron-coder-featherwing-propmaker-bsp"
related_crates = ["lis3dh"]

[[graph_editor.graph.nodes.value.user_data.pinout]]
pins = [5, 9]
ident = "Accelerometer"

[graph_editor.graph.nodes.value.user_data.pinout.interface]
iface_type = "I2C"
direction = "Input"

[[graph_editor.graph.nodes]]
version = 11

[graph_editor.graph.nodes.value]
label = "Feather RP2040"
inputs = []
outputs = [["I2C : Output", { idx = 1, version = 11 }]]

[graph_editor.graph.nodes.value.id]
idx = 2
version = 11

[graph_editor.graph.nodes.value.user_data]
name = "Feather RP2040"
manufacturer = "Adafruit"
is_main_board = true
standard = "Feather"
cpu = "Cortex-M0"
ram = 264
flash = 8000
bsp = "iron-coder-feather-rp2040-bsp"
required_crates = ["adafruit-feather-rp2040", "embedded-hal", "embedded-time", "cortex-m-rt", "cortex-m", "panic-halt"]
related_crates = ["smart-leds", "ws2812-pio"]

[[graph_editor.graph.nodes.value.user_data.pinout]]
pins = [0, 1]

[graph_editor.graph.nodes.value.user_data.pinout.interface]
iface_type = "UART"
direction = "Bidirectional"

[[graph_editor.graph.nodes.value.user_data.pinout]]
pins = [8, 9]

[graph_editor.graph.nodes.value.user_data.pinout.interface]
iface_type = "I2C"
direction = "Output"

[[graph_editor.graph.inputs]]
version = 0

[[graph_editor.graph.inputs]]
version = 13

[graph_editor.graph.inputs.value]
typ = "I2C"
kind = "ConnectionOnly"
shown_inline = true

[graph_editor.graph.inputs.value.id]
idx = 1
version = 13

[graph_editor.graph.inputs.value.value]
pins = [5, 9]
ident = "Accelerometer"

[graph_editor.graph.inputs.value.value.interface]
iface_type = "I2C"
direction = "Input"

[graph_editor.graph.inputs.value.node]
idx = 1
version = 13

[[graph_editor.graph.outputs]]
version = 0

[[graph_editor.graph.outputs]]
version = 11

[graph_editor.graph.outputs.value]
typ = "I2C"

[graph_editor.graph.outputs.value.id]
idx = 1
version = 11

[graph_editor.graph.outputs.value.node]
idx = 2
version = 11

[[graph_editor.graph.connections]]
version = 0

[[graph_editor.graph.connections]]
version = 13

[graph_editor.graph.connections.value]
idx = 1
version = 11

[[graph_editor.node_order]]
idx = 2
version = 11

[[graph_editor.node_order]]
idx = 1
version = 13

[[graph_editor.node_positions]]
version = 0

[[graph_editor.node_positions]]
version = 13

[graph_editor.node_positions.value]
x = 456.9999694824219
y = 145.99998474121094

[[graph_editor.node_positions]]
version = 11

[graph_editor.node_positions.value]
x = 46.0
y = 49.0

[graph_editor.pan_zoom]
zoom = 0.0

[graph_editor.pan_zoom.pan]
x = 0.0
y = 0.0
