name = "a_Test_projec"
location = "/home/carstentb/Projects/iron-coder/projects/a_Test_projec"
current_view = "FileTree"

[system]
connections = []

[[system.boards]]
name = "Feather RP2040"
manufacturer = "Adafruit"
is_main_board = true
standard = "Feather"
cpu = "Cortex-M0"
ram = 264
flash = 8000
required_crates = ["adafruit-feather-rp2040", "embedded-hal", "embedded-time", "cortex-m-rt", "cortex-m", "panic-halt"]
related_crates = ["smart-leds", "ws2812-pio"]

[[system.boards.pinout]]
pins = [0, 1]

[system.boards.pinout.interface]
iface_type = "UART"
direction = "Bidirectional"

[[system.boards.pinout]]
pins = [8, 9]

[system.boards.pinout.interface]
iface_type = "I2C"
direction = "Output"

[[system.boards]]
name = "OLED Featherwing (128x64)"
manufacturer = "Adafruit"
is_main_board = false
standard = "Feather"
pinout = []
related_crates = ["sh1107"]

[[system.boards]]
name = "PropMaker Featherwing"
manufacturer = "Adafruit"
is_main_board = false
standard = "Feather"
related_crates = ["lis3dh"]

[[system.boards.pinout]]
pins = [8, 9]

[system.boards.pinout.interface]
iface_type = "I2C"
direction = "Input"
