name = "asset_testing_2"
location = 'C:\Users\carst\Projects\iron-coder\iron-coder-projects\asset_testing_2'
current_view = "BoardsView"

[system.main_board]
name = "Feather RP2040"
manufacturer = "Adafruit"
is_main_board = true
standard = "Feather"
cpu = "Cortex-M0"
ram = 264
flash = 8000
bsp = "iron-coder-feather-rp2040-bsp"
required_crates = ["adafruit-feather-rp2040", "embedded-hal", "embedded-time", "cortex-m-rt", "cortex-m", "panic-halt"]
related_crates = ["smart-leds", "ws2812-pio"]

[[system.main_board.pinout]]
pins = [0, 1]

[system.main_board.pinout.interface]
iface_type = "UART"
direction = "Bidirectional"

[[system.main_board.pinout]]
pins = [8, 9]

[system.main_board.pinout.interface]
iface_type = "I2C"
direction = "Output"

[[system.peripheral_boards]]
name = "PropMaker Featherwing"
manufacturer = "Adafruit"
is_main_board = false
standard = "Feather"
bsp = "iron-coder-featherwing-propmaker-bsp"
related_crates = ["lis3dh"]

[[system.peripheral_boards.pinout]]
pins = [8, 9]

[system.peripheral_boards.pinout.interface]
iface_type = "I2C"
direction = "Input"

[[system.peripheral_boards]]
name = "OLED Featherwing (128x64)"
manufacturer = "Adafruit"
is_main_board = false
standard = "Feather"
bsp = "iron-coder-featherwing-oled-bsp"
related_crates = ["sh1107"]

[[system.peripheral_boards.pinout]]
pins = [8, 9]

[system.peripheral_boards.pinout.interface]
iface_type = "I2C"
direction = "Input"

[[system.connections]]
interface = "I2C"

[system.connections.start_board]
name = "Feather RP2040"
manufacturer = "Adafruit"
is_main_board = true
standard = "Feather"
cpu = "Cortex-M0"
ram = 264
flash = 8000
bsp = "iron-coder-feather-rp2040-bsp"
required_crates = ["adafruit-feather-rp2040", "embedded-hal", "embedded-time", "cortex-m-rt", "cortex-m", "panic-halt"]
related_crates = ["smart-leds", "ws2812-pio"]

[[system.connections.start_board.pinout]]
pins = [0, 1]

[system.connections.start_board.pinout.interface]
iface_type = "UART"
direction = "Bidirectional"

[[system.connections.start_board.pinout]]
pins = [8, 9]

[system.connections.start_board.pinout.interface]
iface_type = "I2C"
direction = "Output"

[system.connections.end_board]
name = "PropMaker Featherwing"
manufacturer = "Adafruit"
is_main_board = false
standard = "Feather"
bsp = "iron-coder-featherwing-propmaker-bsp"
related_crates = ["lis3dh"]

[[system.connections.end_board.pinout]]
pins = [8, 9]

[system.connections.end_board.pinout.interface]
iface_type = "I2C"
direction = "Input"

[[system.connections]]
interface = "I2C"

[system.connections.start_board]
name = "Feather RP2040"
manufacturer = "Adafruit"
is_main_board = true
standard = "Feather"
cpu = "Cortex-M0"
ram = 264
flash = 8000
bsp = "iron-coder-feather-rp2040-bsp"
required_crates = ["adafruit-feather-rp2040", "embedded-hal", "embedded-time", "cortex-m-rt", "cortex-m", "panic-halt"]
related_crates = ["smart-leds", "ws2812-pio"]

[[system.connections.start_board.pinout]]
pins = [0, 1]

[system.connections.start_board.pinout.interface]
iface_type = "UART"
direction = "Bidirectional"

[[system.connections.start_board.pinout]]
pins = [8, 9]

[system.connections.start_board.pinout.interface]
iface_type = "I2C"
direction = "Output"

[system.connections.end_board]
name = "OLED Featherwing (128x64)"
manufacturer = "Adafruit"
is_main_board = false
standard = "Feather"
bsp = "iron-coder-featherwing-oled-bsp"
related_crates = ["sh1107"]

[[system.connections.end_board.pinout]]
pins = [8, 9]

[system.connections.end_board.pinout.interface]
iface_type = "I2C"
direction = "Input"

[graph_editor]
selected_nodes = []

[[graph_editor.graph.nodes]]
version = 0

[[graph_editor.graph.nodes]]
version = 3

[graph_editor.graph.nodes.value]
label = "Feather RP2040"
inputs = []
outputs = [["I2C : Output", { idx = 1, version = 1 }]]

[graph_editor.graph.nodes.value.id]
idx = 1
version = 3

[graph_editor.graph.nodes.value.user_data]
name = "Feather RP2040"
manufacturer = "Adafruit"
is_main_board = true
standard = "Feather"
cpu = "Cortex-M0"
ram = 264
flash = 8000
bsp = "iron-coder-feather-rp2040-bsp"
required_crates = ["adafruit-feather-rp2040", "embedded-hal", "embedded-time", "cortex-m-rt", "cortex-m", "panic-halt"]
related_crates = ["smart-leds", "ws2812-pio"]

[[graph_editor.graph.nodes.value.user_data.pinout]]
pins = [0, 1]

[graph_editor.graph.nodes.value.user_data.pinout.interface]
iface_type = "UART"
direction = "Bidirectional"

[[graph_editor.graph.nodes.value.user_data.pinout]]
pins = [8, 9]

[graph_editor.graph.nodes.value.user_data.pinout.interface]
iface_type = "I2C"
direction = "Output"

[[graph_editor.graph.nodes]]
version = 1

[graph_editor.graph.nodes.value]
label = "PropMaker Featherwing"
inputs = [["I2C : Input", { idx = 1, version = 1 }]]
outputs = []

[graph_editor.graph.nodes.value.id]
idx = 2
version = 1

[graph_editor.graph.nodes.value.user_data]
name = "PropMaker Featherwing"
manufacturer = "Adafruit"
is_main_board = false
standard = "Feather"
bsp = "iron-coder-featherwing-propmaker-bsp"
related_crates = ["lis3dh"]

[[graph_editor.graph.nodes.value.user_data.pinout]]
pins = [8, 9]

[graph_editor.graph.nodes.value.user_data.pinout.interface]
iface_type = "I2C"
direction = "Input"

[[graph_editor.graph.nodes]]
version = 1

[graph_editor.graph.nodes.value]
label = "OLED Featherwing (128x64)"
inputs = [["I2C : Input", { idx = 2, version = 1 }]]
outputs = []

[graph_editor.graph.nodes.value.id]
idx = 3
version = 1

[graph_editor.graph.nodes.value.user_data]
name = "OLED Featherwing (128x64)"
manufacturer = "Adafruit"
is_main_board = false
standard = "Feather"
bsp = "iron-coder-featherwing-oled-bsp"
related_crates = ["sh1107"]

[[graph_editor.graph.nodes.value.user_data.pinout]]
pins = [8, 9]

[graph_editor.graph.nodes.value.user_data.pinout.interface]
iface_type = "I2C"
direction = "Input"

[[graph_editor.graph.inputs]]
version = 0

[[graph_editor.graph.inputs]]
version = 1

[graph_editor.graph.inputs.value]
typ = "I2C"
kind = "ConnectionOnly"
shown_inline = true

[graph_editor.graph.inputs.value.id]
idx = 1
version = 1

[graph_editor.graph.inputs.value.value]
iface_type = "I2C"
direction = "Input"

[graph_editor.graph.inputs.value.node]
idx = 2
version = 1

[[graph_editor.graph.inputs]]
version = 1

[graph_editor.graph.inputs.value]
typ = "I2C"
kind = "ConnectionOnly"
shown_inline = true

[graph_editor.graph.inputs.value.id]
idx = 2
version = 1

[graph_editor.graph.inputs.value.value]
iface_type = "I2C"
direction = "Input"

[graph_editor.graph.inputs.value.node]
idx = 3
version = 1

[[graph_editor.graph.outputs]]
version = 0

[[graph_editor.graph.outputs]]
version = 1

[graph_editor.graph.outputs.value]
typ = "I2C"

[graph_editor.graph.outputs.value.id]
idx = 1
version = 1

[graph_editor.graph.outputs.value.node]
idx = 1
version = 3

[[graph_editor.graph.connections]]
version = 0

[[graph_editor.graph.connections]]
version = 1

[graph_editor.graph.connections.value]
idx = 1
version = 1

[[graph_editor.graph.connections]]
version = 1

[graph_editor.graph.connections.value]
idx = 1
version = 1

[[graph_editor.node_order]]
idx = 1
version = 3

[[graph_editor.node_order]]
idx = 2
version = 1

[[graph_editor.node_order]]
idx = 3
version = 1

[[graph_editor.node_positions]]
version = 0

[[graph_editor.node_positions]]
version = 3

[graph_editor.node_positions.value]
x = 124.66667175292969
y = 45.00000762939453

[[graph_editor.node_positions]]
version = 1

[graph_editor.node_positions.value]
x = 494.333251953125
y = 63.99998474121094

[[graph_editor.node_positions]]
version = 1

[graph_editor.node_positions.value]
x = 459.0
y = 278.33331298828125

[graph_editor.pan_zoom]
zoom = 0.0

[graph_editor.pan_zoom.pan]
x = 0.0
y = 0.0
