name = "test proj"
location = 'C:\Users\carst\Projects\iron-coder\boards\Adafruit\Feather_RP2040\examples\blinky'

[[boards]]
name = "Feather RP2040"
manufacturer = "Adafruit"
standard = "Feather"
cpu = "Cortex-M0"
ram = 264
flash = 8000

[[boards]]
name = "Feather nRF52840 Express"
manufacturer = "Adafruit"
standard = "Feather"
