name = "oled-testing"
location = 'C:\Users\carst\Projects\iron-coder\iron-coder-projects\oled-testing'
current_view = "BoardsView"

[system]
connections = []

[[system.boards]]
name = "Feather RP2040"
manufacturer = "Adafruit"
is_main_board = true
standard = "Feather"
cpu = "Cortex-M0"
ram = 264
flash = 8000
bsp = "iron-coder-feather-rp2040-bsp"
required_crates = ["adafruit-feather-rp2040", "embedded-hal", "embedded-time", "cortex-m-rt", "cortex-m", "panic-halt"]
related_crates = ["smart-leds", "ws2812-pio"]

[[system.boards.pinout]]
pins = [0, 1]

[system.boards.pinout.interface]
iface_type = "UART"
direction = "Bidirectional"

[[system.boards.pinout]]
pins = [8, 9]

[system.boards.pinout.interface]
iface_type = "I2C"
direction = "Output"

[[system.boards]]
name = "OLED Featherwing (128x64)"
manufacturer = "Adafruit"
is_main_board = false
standard = "Feather"
pinout = []
bsp = "iron-coder-featherwing-oled-bsp"
related_crates = ["sh1107"]

[graph_editor]
selected_nodes = []

[[graph_editor.graph.nodes]]
version = 0

[[graph_editor.graph.nodes]]
version = 1

[graph_editor.graph.nodes.value]
label = "Feather RP2040"
inputs = []
outputs = [["I2C : Output", { idx = 1, version = 1 }]]

[graph_editor.graph.nodes.value.id]
idx = 1
version = 1

[graph_editor.graph.nodes.value.user_data]
name = "Feather RP2040"
manufacturer = "Adafruit"
is_main_board = true
standard = "Feather"
cpu = "Cortex-M0"
ram = 264
flash = 8000
bsp = "iron-coder-feather-rp2040-bsp"
required_crates = ["adafruit-feather-rp2040", "embedded-hal", "embedded-time", "cortex-m-rt", "cortex-m", "panic-halt"]
related_crates = ["smart-leds", "ws2812-pio"]

[[graph_editor.graph.nodes.value.user_data.pinout]]
pins = [0, 1]

[graph_editor.graph.nodes.value.user_data.pinout.interface]
iface_type = "UART"
direction = "Bidirectional"

[[graph_editor.graph.nodes.value.user_data.pinout]]
pins = [8, 9]

[graph_editor.graph.nodes.value.user_data.pinout.interface]
iface_type = "I2C"
direction = "Output"

[[graph_editor.graph.nodes]]
version = 1

[graph_editor.graph.nodes.value]
label = "OLED Featherwing (128x64)"
inputs = []
outputs = []

[graph_editor.graph.nodes.value.id]
idx = 2
version = 1

[graph_editor.graph.nodes.value.user_data]
name = "OLED Featherwing (128x64)"
manufacturer = "Adafruit"
is_main_board = false
standard = "Feather"
pinout = []
bsp = "iron-coder-featherwing-oled-bsp"
related_crates = ["sh1107"]

[[graph_editor.graph.inputs]]
version = 0

[[graph_editor.graph.outputs]]
version = 0

[[graph_editor.graph.outputs]]
version = 1

[graph_editor.graph.outputs.value]
typ = "I2C"

[graph_editor.graph.outputs.value.id]
idx = 1
version = 1

[graph_editor.graph.outputs.value.node]
idx = 1
version = 1

[[graph_editor.graph.connections]]
version = 0

[[graph_editor.node_order]]
idx = 2
version = 1

[[graph_editor.node_order]]
idx = 1
version = 1

[[graph_editor.node_positions]]
version = 0

[[graph_editor.node_positions]]
version = 1

[graph_editor.node_positions.value]
x = 146.33331298828125
y = 146.6666717529297

[[graph_editor.node_positions]]
version = 1

[graph_editor.node_positions.value]
x = 527.0
y = 215.66665649414063

[graph_editor.pan_zoom]
zoom = 0.0

[graph_editor.pan_zoom.pan]
x = 0.0
y = 0.0
